lib/puppet/provider/acl/posixacl.rb
=> Check if a path exists before calling getfacl

README.org, lib/puppet/provider/acl.rb, lib/puppet/provider/acl/genericacl.rb, lib/puppet/provider/posix_acl/genericacl.rb, lib/puppet/provider/posix_acl/posixacl.rb, lib/puppet/type/acl.rb, lib/puppet/type/posix_acl.rb, manifests/requirements.pp, metadata.json, spec/unit/puppet/provider/posixacl_spec.rb, spec/unit/puppet/type/acl_spec.rb
Looks like I forgot to push these commits and do a PR. It also fixes some other issues and could use some review.
=> Rename to voxpupuli-posix_acl

lib/puppet/provider/posix_acl/genericacl.rb, lib/puppet/provider/posix_acl/posixacl.rb, lib/puppet/type/posix_acl.rb, spec/unit/puppet/provider/posixacl_spec.rb, spec/unit/puppet/type/acl_spec.rb
Reverts voxpupuli/puppet-posix_acl#37
didn't mean to squash. :/
=> Revert "Rubocop auto fixes"

lib/puppet/provider/posix_acl/posixacl.rb, lib/puppet/type/posix_acl.rb
This is *not* an autofix, so does need reviewing.
=> Rubocop: Fix Style/GuardClause

lib/puppet/type/posix_acl.rb
=> Rubocop: Fix Style/PredicateName

.github/PULL_REQUEST_TEMPLATE.md, .msync.yml, .rubocop.yml, .sync.yml, .travis.yml, Gemfile, lib/puppet/type/posix_acl.rb, spec/acceptance/nodesets/docker/ubuntu-16.04.yml, spec/acceptance/nodesets/fedora-26-x64.yml, spec/acceptance/nodesets/fedora-27-x64.yml, spec/unit/puppet/type/acl_spec.rb
=> modulesync 1.9.0

CHANGELOG.md, metadata.json
=> release 0.1.0

metadata.json
This PR expands the operating system support to include Debian 9 and 10
I've tested both OS releases using puppet masterless, both worked without issues.
thanks!
=> Expand the operating system support to include Debian 9 and 10

.github/CONTRIBUTING.md, .rubocop.yml, Gemfile, lib/puppet/provider/posix_acl/posixacl.rb, lib/puppet/type/posix_acl.rb
=> modulesync 2.10.1

CHANGELOG.md
=> release 1.0.1

.github/SECURITY.md, .msync.yml, .rubocop.yml, .travis.yml, Gemfile, spec/unit/puppet/type/acl_spec.rb
=> modulesync 3.0.0

lib/puppet/provider/posix_acl/posixacl.rb
=> Changed to osfamily to make it work on oracle linux systems

metadata.json
changing version compatibility as requested in #91
Fixes #91
=> Mark compatible with Puppet 7

.editorconfig, .github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, .msync.yml, .overcommit.yml, .pmtignore, .rspec, .rspec_parallel, .rubocop.yml, .yardopts, Dockerfile, Gemfile, Rakefile, lib/puppet/provider/posix_acl/posixacl.rb, metadata.json, spec/spec_helper.rb
=> Add support for Debian 11, RedHat 8 (and derivatives)

.github/workflows/ci.yml, .sync.yml, spec/acceptance/requirements_spec.rb, spec/spec_helper_acceptance.rb
=> Manage spec_helper_acceptance via modulesync / Enable basic acceptance test

lib/puppet/type/posix_acl.rb
=> Fix typo in documentation

spec/acceptance/purge_posix_acl_spec.rb
=> Add test to verify purging ACLs works

.github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .msync.yml, Dockerfile, Gemfile, Rakefile, lib/puppet/type/posix_acl.rb, spec/spec_helper.rb
=> modulesync 5.4.0

metadata.json
=> Add EL9/Rocky/Alma support

metadata.json
=> Add Ubuntu 20.04/22.04 & Debian 12
